FORMAT: 1A

# Gist Fox API
Gist Fox API is a **pastes service** similar to [GitHub's Gist](http://gist.github.com).

## Authentication
*Gist Fox API* uses OAuth Authorization. First you create a new (or acquire existing) OAuth token using Basic Authentication. After you have acquired your token you can use it to access other resources within token' scope.

## Media Types
Where applicable this API uses the [HAL+JSON](https://github.com/mikekelly/hal_specification/blob/master/hal_specification.md) media-type to represent resources states and affordances.

Requests with a message-body are using plain JSON to set or update resource states.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

# Gist Fox API Root [/]
Gist Fox API entry point.

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the HTTP Link header and 
HAL links.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)
    + Headers
    
            Link: <http:/api.gistfox.com/>;rel="self",<http:/api.gistfox.com/gists>;rel="gists",<http:/api.gistfox.com/authorization>;rel="authorization"

    + Body

            {
                "_links": {
                    "self": { "href": "/" },
                    "gists": { "href": "/gists?{since}", "templated": true },
                    "authorization": { "href": "/authorization"}
                }
            }

# Group Gist
Gist-related resources of *Gist Fox API*.

## List User Gist [/users/{name}/gists{?access_token}] 
### List All Gists [GET]
+ Parameters
    + access_token (optional, string) ... Timestamp in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ` Only gists updated at or after this time are returned.

+ Response 200

    [Gists Collection][]
    
## Gist [/gists/{id}{?access_token}]
A single Gist object. The Gist resource is the central resource in the Gist Fox API. It represents one paste - a single text note.

The Gist resource has the following attributes: 

- id
- created_at
- description
- content

The states *id* and *created_at* are assigned by the Gist Fox API at the moment of creation. 

+ Parameters
    + id (string) ... ID of the Gist in the form of a hash.
    + access_token (string, optional) ... Gist Fox API access token.

+ Model (application/json)

    HAL+JSON representation of Gist Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.

    + Body

            {
            
                "url": "https://api.github.com/gists/68f487656bacb6535c7e",
                "forks_url": "https://api.github.com/gists/68f487656bacb6535c7e/forks",
                "commits_url": "https://api.github.com/gists/68f487656bacb6535c7e/commits",
                "id": "68f487656bacb6535c7e",
                "git_pull_url": "https://gist.github.com/68f487656bacb6535c7e.git",
                "git_push_url": "https://gist.github.com/68f487656bacb6535c7e.git",
                "html_url": "https://gist.github.com/68f487656bacb6535c7e",
                "files": 
            
            {
            
                "README.md": 
            
            {
            
                "filename": "README.md",
                "type": "text/plain",
                "language": "Markdown",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/68f487656bacb6535c7e/raw/cf64e461e193285024ec7c7e7362b5ee134cf753/README.md",
                "size": 310,
                "truncated": false,
                "content": "1. `sudo pip install onetimepass`\n2. 需要okta绑定 google authenticator 时 QR code里面的16位的 secret, android 用 barcode scaner 一扫就知道了\n3. 填到 auth.py 里\n4. 填用户名密码到 inputs.txt\n5. 以后每次运行 ./vpn connect (用 zsh or fish) 就登上了\n7. `vpn diconnect` 下线"
            
            },
            "auth.py":
            {
            
                "filename": "auth.py",
                "type": "application/x-python",
                "language": "Python",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/68f487656bacb6535c7e/raw/7e6b7cb12c4f358749b0895ae10b78d2f9a4ae61/auth.py",
                "size": 99,
                "truncated": false,
                "content": "import os\nimport onetimepass as otp\nmy_secret = 'SECRET_FROM_QRCODE'\nprint otp.get_totp(my_secret)\n"
            
            },
            "inputs.txt":
            {
            
                "filename": "inputs.txt",
                "type": "text/plain",
                "language": "Text",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/68f487656bacb6535c7e/raw/9d3e22652a387d6643bf6ca518eac909a0968f78/inputs.txt",
                "size": 45,
                "truncated": false,
                "content": "y\nUSENAME\nPASSWORD\n3\nAUTHENTICATOR_CODE\nexit\n"
            
            },
            "vpn":
            
                {
                    "filename": "vpn",
                    "type": "text/plain",
                    "language": "Shell",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/68f487656bacb6535c7e/raw/51ecd4685958eb7e51fe2dadac7a45aaca591bd7/vpn",
                    "size": 157,
                    "truncated": false,
                    "content": "#!/bin/zsh\nanswers=$(sed 's/AUTHENTICATOR_CODE/'$(python auth.py)'/g' inputs.txt)\necho $answers | /opt/cisco/anyconnect/bin/vpn -s $1 bjvpn.thoughtworks.com\n"
                }
            
            },
            "public": false,
            "created_at": "2014-12-04T09:25:04Z",
            "updated_at": "2014-12-08T03:32:32Z",
            "description": "thoughtworks VPN 1 click login script",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/68f487656bacb6535c7e/comments",
            "owner":
            {
            
                "login": "jcouyang",
                "id": 1235045,
                "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jcouyang",
                "html_url": "https://github.com/jcouyang",
                "followers_url": "https://api.github.com/users/jcouyang/followers",
                "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                "repos_url": "https://api.github.com/users/jcouyang/repos",
                "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                "type": "User",
                "site_admin": false
            
            },
            "forks": [ ],
            "history":
            [
            
            {
            
                "user": 
            
            {
            
                "login": "jcouyang",
                "id": 1235045,
                "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jcouyang",
                "html_url": "https://github.com/jcouyang",
                "followers_url": "https://api.github.com/users/jcouyang/followers",
                "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                "repos_url": "https://api.github.com/users/jcouyang/repos",
                "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                "type": "User",
                "site_admin": false
            
            },
            "version": "40a55838e69d0ccc731fde38b0b404753fb4f5f5",
            "committed_at": "2014-12-08T03:32:32Z",
            "change_status":
            
                {
                    "total": 2,
                    "additions": 1,
                    "deletions": 1
                },
                "url": "https://api.github.com/gists/68f487656bacb6535c7e/40a55838e69d0ccc731fde38b0b404753fb4f5f5"
            
            },
            {
            
                "user": 
            
            {
            
                "login": "jcouyang",
                "id": 1235045,
                "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jcouyang",
                "html_url": "https://github.com/jcouyang",
                "followers_url": "https://api.github.com/users/jcouyang/followers",
                "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                "repos_url": "https://api.github.com/users/jcouyang/repos",
                "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                "type": "User",
                "site_admin": false
            
            },
            "version": "bd3755f04c15d6f1cf17cee2dcf14754155e5d77",
            "committed_at": "2014-12-05T15:58:28Z",
            "change_status":
            
                {
                    "total": 6,
                    "additions": 6,
                    "deletions": 0
                },
                "url": "https://api.github.com/gists/68f487656bacb6535c7e/bd3755f04c15d6f1cf17cee2dcf14754155e5d77"
            
            },
            {
            
                "user": 
            
            {
            
                "login": "jcouyang",
                "id": 1235045,
                "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jcouyang",
                "html_url": "https://github.com/jcouyang",
                "followers_url": "https://api.github.com/users/jcouyang/followers",
                "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                "repos_url": "https://api.github.com/users/jcouyang/repos",
                "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                "type": "User",
                "site_admin": false
            
            },
            "version": "37d624b4fd8253dae6a53289454b993c38cccb56",
            "committed_at": "2014-12-04T09:25:04Z",
            "change_status":
            
                        {
                            "total": 13,
                            "additions": 13,
                            "deletions": 0
                        },
                        "url": "https://api.github.com/gists/68f487656bacb6535c7e/37d624b4fd8253dae6a53289454b993c38cccb56"
                    }
                ]
            
            }
            
### Retrieve a Single Gist [GET]
+ Response 200
    
    [Gist][]

### Edit a Gist [PATCH]
To update a Gist send a JSON with updated value for one or more of the Gist resource attributes. All attributes values (states) from the previous version of this Gist are carried over by default if not included in the hash.

+ Request (application/json)

        {
            "content": "Updated file contents"
        }

+ Response 200
    
    [Gist][]

### Delete a Gist [DELETE]
+ Response 204

## Gists Collection [/gists{?access_token,since}]
Collection of all Gists.

The Gist Collection resource has the following attribute:

- total

In addition it **embeds** *Gist Resources* in the Gist Fox API.

+ Model (application/json)

            [
            
            {
            
                "url": "https://api.github.com/gists/0289802edf83b3aaeecc",
                "forks_url": "https://api.github.com/gists/0289802edf83b3aaeecc/forks",
                "commits_url": "https://api.github.com/gists/0289802edf83b3aaeecc/commits",
                "id": "0289802edf83b3aaeecc",
                "git_pull_url": "https://gist.github.com/0289802edf83b3aaeecc.git",
                "git_push_url": "https://gist.github.com/0289802edf83b3aaeecc.git",
                "html_url": "https://gist.github.com/0289802edf83b3aaeecc",
                "files": 
            
            {
            
                "clean-mac-download-log.md": 
            
                {
                    "filename": "clean-mac-download-log.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/0289802edf83b3aaeecc/raw/3c8760120464426d6558c286fa4daf47307e79bd/clean-mac-download-log.md",
                    "size": 755
                }
            
            },
            "public": true,
            "created_at": "2014-11-14T06:51:52Z",
            "updated_at": "2014-12-15T00:55:53Z",
            "description": "清空 mac 历史下载记录",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/0289802edf83b3aaeecc/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/2208bd0aa2748c2998a5",
                "forks_url": "https://api.github.com/gists/2208bd0aa2748c2998a5/forks",
                "commits_url": "https://api.github.com/gists/2208bd0aa2748c2998a5/commits",
                "id": "2208bd0aa2748c2998a5",
                "git_pull_url": "https://gist.github.com/2208bd0aa2748c2998a5.git",
                "git_push_url": "https://gist.github.com/2208bd0aa2748c2998a5.git",
                "html_url": "https://gist.github.com/2208bd0aa2748c2998a5",
                "files": 
            
            {
            
                "emacs-24-4.md": 
            
                {
                    "filename": "emacs-24-4.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/2208bd0aa2748c2998a5/raw/6ba98ae88506342bf543caaab520e4aac12b0e23/emacs-24-4.md",
                    "size": 1832
                }
            
            },
            "public": true,
            "created_at": "2014-10-25T08:37:00Z",
            "updated_at": "2014-11-11T00:51:33Z",
            "description": "emacs 24.4 新特性",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/2208bd0aa2748c2998a5/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/566cb81df06ff473254b",
                "forks_url": "https://api.github.com/gists/566cb81df06ff473254b/forks",
                "commits_url": "https://api.github.com/gists/566cb81df06ff473254b/commits",
                "id": "566cb81df06ff473254b",
                "git_pull_url": "https://gist.github.com/566cb81df06ff473254b.git",
                "git_push_url": "https://gist.github.com/566cb81df06ff473254b.git",
                "html_url": "https://gist.github.com/566cb81df06ff473254b",
                "files": 
            
            {
            
                "ansi-term.ti": 
            
            {
            
                "filename": "ansi-term.ti",
                "type": "text/plain",
                "language": null,
                "raw_url": "https://gist.githubusercontent.com/jcouyang/566cb81df06ff473254b/raw/83f26f4e140e0c663ff75fc28c8072d67493d064/ansi-term.ti",
                "size": 1456
            
            },
            "fix-weird-4m-in-emacs-ansi-term.md":
            
                {
                    "filename": "fix-weird-4m-in-emacs-ansi-term.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/566cb81df06ff473254b/raw/8368a0933fd22d4121bfeb789acaf16ef26185ab/fix-weird-4m-in-emacs-ansi-term.md",
                    "size": 146
                }
            
            },
            "public": true,
            "created_at": "2014-09-28T01:46:35Z",
            "updated_at": "2014-11-18T09:05:39Z",
            "description": "fix weird charactor 4m in emacs ansi-term",
            "comments": 1,
            "user": null,
            "comments_url": "https://api.github.com/gists/566cb81df06ff473254b/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/34686f695cd28309759e",
                "forks_url": "https://api.github.com/gists/34686f695cd28309759e/forks",
                "commits_url": "https://api.github.com/gists/34686f695cd28309759e/commits",
                "id": "34686f695cd28309759e",
                "git_pull_url": "https://gist.github.com/34686f695cd28309759e.git",
                "git_push_url": "https://gist.github.com/34686f695cd28309759e.git",
                "html_url": "https://gist.github.com/34686f695cd28309759e",
                "files": 
            
            {
            
                "3-reason-to-use-jest-to-test-your-javascript.md": 
            
                {
                    "filename": "3-reason-to-use-jest-to-test-your-javascript.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/34686f695cd28309759e/raw/8a74ab959a0245b01a0c75ea3d5a2770f322e3ef/3-reason-to-use-jest-to-test-your-javascript.md",
                    "size": 7789
                }
            
            },
            "public": true,
            "created_at": "2014-08-19T12:08:34Z",
            "updated_at": "2014-12-15T10:03:05Z",
            "description": "用 jest 轻松测试 JavaScript",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/34686f695cd28309759e/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/6365feec88bf86a4ae59",
                "forks_url": "https://api.github.com/gists/6365feec88bf86a4ae59/forks",
                "commits_url": "https://api.github.com/gists/6365feec88bf86a4ae59/commits",
                "id": "6365feec88bf86a4ae59",
                "git_pull_url": "https://gist.github.com/6365feec88bf86a4ae59.git",
                "git_push_url": "https://gist.github.com/6365feec88bf86a4ae59.git",
                "html_url": "https://gist.github.com/6365feec88bf86a4ae59",
                "files": 
            
            {
            
                "moz-request.js": 
            
                {
                    "filename": "moz-request.js",
                    "type": "application/javascript",
                    "language": "JavaScript",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/6365feec88bf86a4ae59/raw/f6dda884dcd7b7eb07fcfb61bdec6891818961ae/moz-request.js",
                    "size": 313
                }
            
            },
            "public": true,
            "created_at": "2014-08-07T14:33:07Z",
            "updated_at": "2014-08-16T12:47:31Z",
            "description": "",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/6365feec88bf86a4ae59/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/0b2e3c26f704f5d1008e",
                "forks_url": "https://api.github.com/gists/0b2e3c26f704f5d1008e/forks",
                "commits_url": "https://api.github.com/gists/0b2e3c26f704f5d1008e/commits",
                "id": "0b2e3c26f704f5d1008e",
                "git_pull_url": "https://gist.github.com/0b2e3c26f704f5d1008e.git",
                "git_push_url": "https://gist.github.com/0b2e3c26f704f5d1008e.git",
                "html_url": "https://gist.github.com/0b2e3c26f704f5d1008e",
                "files": 
            
            {
            
                "monad.md": 
            
                {
                    "filename": "monad.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/0b2e3c26f704f5d1008e/raw/c8ec69a3d41b364f049b5bff4a3d3913e3ddceb5/monad.md",
                    "size": 6142
                }
            
            },
            "public": true,
            "created_at": "2014-07-21T14:53:02Z",
            "updated_at": "2014-10-28T13:40:17Z",
            "description": "你造Promise 就是 Monad 吗",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/0b2e3c26f704f5d1008e/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/edd59391826d8c9e6045",
                "forks_url": "https://api.github.com/gists/edd59391826d8c9e6045/forks",
                "commits_url": "https://api.github.com/gists/edd59391826d8c9e6045/commits",
                "id": "edd59391826d8c9e6045",
                "git_pull_url": "https://gist.github.com/edd59391826d8c9e6045.git",
                "git_push_url": "https://gist.github.com/edd59391826d8c9e6045.git",
                "html_url": "https://gist.github.com/edd59391826d8c9e6045",
                "files": 
            
            {
            
                "vpn": 
            
                {
                    "filename": "vpn",
                    "type": "text/plain",
                    "language": "Shell",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/edd59391826d8c9e6045/raw/6b355c011e90d0ad10d60bfe38ffe024a74e8839/vpn",
                    "size": 105
                }
            
            },
            "public": true,
            "created_at": "2014-07-14T05:45:04Z",
            "updated_at": "2014-12-02T01:37:07Z",
            "description": "connect cisco anyconnect in terminal",
            "comments": 3,
            "user": null,
            "comments_url": "https://api.github.com/gists/edd59391826d8c9e6045/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/b56a830cd55bd230049f",
                "forks_url": "https://api.github.com/gists/b56a830cd55bd230049f/forks",
                "commits_url": "https://api.github.com/gists/b56a830cd55bd230049f/commits",
                "id": "b56a830cd55bd230049f",
                "git_pull_url": "https://gist.github.com/b56a830cd55bd230049f.git",
                "git_push_url": "https://gist.github.com/b56a830cd55bd230049f.git",
                "html_url": "https://gist.github.com/b56a830cd55bd230049f",
                "files": 
            
            {
            
                "why-curry-helps.md": 
            
                {
                    "filename": "why-curry-helps.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/b56a830cd55bd230049f/raw/4787cbf083fd40bf30ac9dd4cec0e9a710cc6d18/why-curry-helps.md",
                    "size": 3294
                }
            
            },
            "public": true,
            "created_at": "2014-07-02T09:15:52Z",
            "updated_at": "2014-12-05T03:40:26Z",
            "description": "为什么要柯里化（why-curry-helps）slide http://git.io/why-curry-helps :chart_with_upwards_trend:",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/b56a830cd55bd230049f/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/2858ee70bfda67097e47",
                "forks_url": "https://api.github.com/gists/2858ee70bfda67097e47/forks",
                "commits_url": "https://api.github.com/gists/2858ee70bfda67097e47/commits",
                "id": "2858ee70bfda67097e47",
                "git_pull_url": "https://gist.github.com/2858ee70bfda67097e47.git",
                "git_push_url": "https://gist.github.com/2858ee70bfda67097e47.git",
                "html_url": "https://gist.github.com/2858ee70bfda67097e47",
                "files": 
            
            {
            
                "replace_evernote.md": 
            
                {
                    "filename": "replace_evernote.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/2858ee70bfda67097e47/raw/994e0e8c1ea5cee0a62ac1772f53bc4469d8e354/replace_evernote.md",
                    "size": 1146
                }
            
            },
            "public": true,
            "created_at": "2014-06-18T04:52:33Z",
            "updated_at": "2014-12-07T08:34:12Z",
            "description": "Why do we still need Evernote since there is awesome gist.github.com",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/2858ee70bfda67097e47/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/8e6e91c10ff3d34dc7e2",
                "forks_url": "https://api.github.com/gists/8e6e91c10ff3d34dc7e2/forks",
                "commits_url": "https://api.github.com/gists/8e6e91c10ff3d34dc7e2/commits",
                "id": "8e6e91c10ff3d34dc7e2",
                "git_pull_url": "https://gist.github.com/8e6e91c10ff3d34dc7e2.git",
                "git_push_url": "https://gist.github.com/8e6e91c10ff3d34dc7e2.git",
                "html_url": "https://gist.github.com/8e6e91c10ff3d34dc7e2",
                "files": 
            
            {
            
                "00 Setup Env.md": 
            
            {
            
                "filename": "00 Setup Env.md",
                "type": "text/plain",
                "language": "Markdown",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/8e6e91c10ff3d34dc7e2/raw/298d5b3d40ff51f8fd7783408fff9fcab4cc4db2/00%20Setup%20Env.md",
                "size": 2652
            
            },
            "01 Get Familia with Template and Promise.md":
            {
            
                "filename": "01 Get Familia with Template and Promise.md",
                "type": "text/plain",
                "language": "Markdown",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/8e6e91c10ff3d34dc7e2/raw/1e3cd84914133a0842b2acaa302c8153bc667abb/01%20Get%20Familia%20with%20Template%20and%20Promise.md",
                "size": 2648
            
            },
            "02 Play-with-Event.markdown":
            {
            
                "filename": "02 Play-with-Event.markdown",
                "type": "text/plain",
                "language": "Markdown",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/8e6e91c10ff3d34dc7e2/raw/89482ec9933d54f82a50019469b1c27d8c616aff/02%20Play-with-Event.markdown",
                "size": 1389
            
            },
            "03 Prettify-Your-Code.md":
            {
            
                "filename": "03 Prettify-Your-Code.md",
                "type": "text/plain",
                "language": "Markdown",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/8e6e91c10ff3d34dc7e2/raw/e21581e57508c75a10ef93044e222f7ad5f364ea/03%20Prettify-Your-Code.md",
                "size": 6354
            
            },
            "04 We-Need-Router.md":
            {
            
                "filename": "04 We-Need-Router.md",
                "type": "text/plain",
                "language": "Markdown",
                "raw_url": "https://gist.githubusercontent.com/jcouyang/8e6e91c10ff3d34dc7e2/raw/410bb5d3e5588b70a28061f0c0bf7eda3d2783fc/04%20We-Need-Router.md",
                "size": 2716
            
            },
            "05 Model.md":
            
                {
                    "filename": "05 Model.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/8e6e91c10ff3d34dc7e2/raw/ed05dee3f846180f6027642d109f7c2da8d39ea4/05%20Model.md",
                    "size": 320
                }
            
            },
            "public": true,
            "created_at": "2014-06-13T09:23:20Z",
            "updated_at": "2014-10-28T13:42:58Z",
            "description": "Build Yourself a Backbone.js Step by Step",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/8e6e91c10ff3d34dc7e2/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/10816025",
                "forks_url": "https://api.github.com/gists/10816025/forks",
                "commits_url": "https://api.github.com/gists/10816025/commits",
                "id": "10816025",
                "git_pull_url": "https://gist.github.com/10816025.git",
                "git_push_url": "https://gist.github.com/10816025.git",
                "html_url": "https://gist.github.com/10816025",
                "files": 
            
            {
            
                "atom workspaceView events": 
            
                {
                    "filename": "atom workspaceView events",
                    "type": "text/plain",
                    "language": null,
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/10816025/raw/97c24ab360d5ba63dbe1b5f67b719516cd597d56/atom%20workspaceView%20events",
                    "size": 6082
                }
            
            },
            "public": true,
            "created_at": "2014-04-16T06:21:44Z",
            "updated_at": "2014-12-13T04:01:08Z",
            "description": "the atom workspaceView events",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/10816025/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/10696702",
                "forks_url": "https://api.github.com/gists/10696702/forks",
                "commits_url": "https://api.github.com/gists/10696702/commits",
                "id": "10696702",
                "git_pull_url": "https://gist.github.com/10696702.git",
                "git_push_url": "https://gist.github.com/10696702.git",
                "html_url": "https://gist.github.com/10696702",
                "files": 
            
            {
            
                "learnjulia.jl": 
            
                {
                    "filename": "learnjulia.jl",
                    "type": "text/plain",
                    "language": "Julia",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/10696702/raw/8f76afd25bc0fdd164cb32f12ca12ad6758274d9/learnjulia.jl",
                    "size": 19460
                }
            
            },
            "public": true,
            "created_at": "2014-04-15T02:18:00Z",
            "updated_at": "2014-06-20T15:50:31Z",
            "description": "Y 分钟学 Julia",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/10696702/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9968699",
                "forks_url": "https://api.github.com/gists/9968699/forks",
                "commits_url": "https://api.github.com/gists/9968699/commits",
                "id": "9968699",
                "git_pull_url": "https://gist.github.com/9968699.git",
                "git_push_url": "https://gist.github.com/9968699.git",
                "html_url": "https://gist.github.com/9968699",
                "files": 
            
            {
            
                "all github 887 emojis.md": 
            
                {
                    "filename": "all github 887 emojis.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9968699/raw/183c52932701fd95122ffa293a8137cc667a0ec0/all%20github%20887%20emojis.md",
                    "size": 10692
                }
            
            },
            "public": true,
            "created_at": "2014-04-04T05:30:50Z",
            "updated_at": "2014-08-24T14:23:25Z",
            "description": "all github 887 emoji",
            "comments": 1,
            "user": null,
            "comments_url": "https://api.github.com/gists/9968699/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9914102",
                "forks_url": "https://api.github.com/gists/9914102/forks",
                "commits_url": "https://api.github.com/gists/9914102/commits",
                "id": "9914102",
                "git_pull_url": "https://gist.github.com/9914102.git",
                "git_push_url": "https://gist.github.com/9914102.git",
                "html_url": "https://gist.github.com/9914102",
                "files": 
            
            {
            
                "2013-05-25-flash-dd-wrt-and-install-transmission.md": 
            
                {
                    "filename": "2013-05-25-flash-dd-wrt-and-install-transmission.md",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9914102/raw/e3828f67461ad166268ea4514586a92732b2c41b/2013-05-25-flash-dd-wrt-and-install-transmission.md",
                    "size": 4261
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:36:29Z",
            "updated_at": "2014-11-21T01:20:31Z",
            "description": "flash dd-wrt and install transmission in WNR2200 router",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9914102/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9914091",
                "forks_url": "https://api.github.com/gists/9914091/forks",
                "commits_url": "https://api.github.com/gists/9914091/commits",
                "id": "9914091",
                "git_pull_url": "https://gist.github.com/9914091.git",
                "git_push_url": "https://gist.github.com/9914091.git",
                "html_url": "https://gist.github.com/9914091",
                "files": 
            
            {
            
                "2012-12-31-node-dot-js-vs-tornado-vs-php.markdown": 
            
                {
                    "filename": "2012-12-31-node-dot-js-vs-tornado-vs-php.markdown",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9914091/raw/2863597773750aaf6333b6f37198c9c646aa19a4/2012-12-31-node-dot-js-vs-tornado-vs-php.markdown",
                    "size": 11613
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:35:50Z",
            "updated_at": "2014-10-28T13:44:05Z",
            "description": "为什么事件驱动服务器这么火",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9914091/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9913972",
                "forks_url": "https://api.github.com/gists/9913972/forks",
                "commits_url": "https://api.github.com/gists/9913972/commits",
                "id": "9913972",
                "git_pull_url": "https://gist.github.com/9913972.git",
                "git_push_url": "https://gist.github.com/9913972.git",
                "html_url": "https://gist.github.com/9913972",
                "files": 
            
            {
            
                "2014-02-09-use-q-promise-to-flat-you-async-ajax-and-make-tdd-easy.org": 
            
                {
                    "filename": "2014-02-09-use-q-promise-to-flat-you-async-ajax-and-make-tdd-easy.org",
                    "type": "text/plain",
                    "language": "Org",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9913972/raw/4ac73a1fda7906ea6ea9e893d99c0c52d5173733/2014-02-09-use-q-promise-to-flat-you-async-ajax-and-make-tdd-easy.org",
                    "size": 5064
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:29:02Z",
            "updated_at": "2014-04-01T13:29:02Z",
            "description": "Why Promises will make async easy",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9913972/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9913920",
                "forks_url": "https://api.github.com/gists/9913920/forks",
                "commits_url": "https://api.github.com/gists/9913920/commits",
                "id": "9913920",
                "git_pull_url": "https://gist.github.com/9913920.git",
                "git_push_url": "https://gist.github.com/9913920.git",
                "html_url": "https://gist.github.com/9913920",
                "files": 
            
            {
            
                "2013-11-27-bdd-using-jasmine-jquery.org": 
            
                {
                    "filename": "2013-11-27-bdd-using-jasmine-jquery.org",
                    "type": "text/plain",
                    "language": "Org",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9913920/raw/682d722fd2bf5f4bd94bc5533ba2e67ad26e3bed/2013-11-27-bdd-using-jasmine-jquery.org",
                    "size": 5363
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:24:23Z",
            "updated_at": "2014-04-12T03:44:22Z",
            "description": "BDD using jasmine jquery",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9913920/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9913882",
                "forks_url": "https://api.github.com/gists/9913882/forks",
                "commits_url": "https://api.github.com/gists/9913882/commits",
                "id": "9913882",
                "git_pull_url": "https://gist.github.com/9913882.git",
                "git_push_url": "https://gist.github.com/9913882.git",
                "html_url": "https://gist.github.com/9913882",
                "files": 
            
            {
            
                "2013-09-13-this-blog-can-configure-emacs.org": 
            
                {
                    "filename": "2013-09-13-this-blog-can-configure-emacs.org",
                    "type": "text/plain",
                    "language": "Org",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9913882/raw/e4e1f226fde0d0263305c581b8a06e96e7d71fe9/2013-09-13-this-blog-can-configure-emacs.org",
                    "size": 1702
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:22:29Z",
            "updated_at": "2014-04-01T13:22:29Z",
            "description": "emacs auto config",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9913882/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9913872",
                "forks_url": "https://api.github.com/gists/9913872/forks",
                "commits_url": "https://api.github.com/gists/9913872/commits",
                "id": "9913872",
                "git_pull_url": "https://gist.github.com/9913872.git",
                "git_push_url": "https://gist.github.com/9913872.git",
                "html_url": "https://gist.github.com/9913872",
                "files": 
            
            {
            
                "2013-09-05-bootstrap-your-android-development.org": 
            
                {
                    "filename": "2013-09-05-bootstrap-your-android-development.org",
                    "type": "text/plain",
                    "language": "Org",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9913872/raw/21c4e81336cbbb5149af04384b7c9fdbb30f75bf/2013-09-05-bootstrap-your-android-development.org",
                    "size": 11557
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:21:45Z",
            "updated_at": "2014-11-12T12:27:02Z",
            "description": "快速开发android应用",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9913872/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            },
            {
            
                "url": "https://api.github.com/gists/9913820",
                "forks_url": "https://api.github.com/gists/9913820/forks",
                "commits_url": "https://api.github.com/gists/9913820/commits",
                "id": "9913820",
                "git_pull_url": "https://gist.github.com/9913820.git",
                "git_push_url": "https://gist.github.com/9913820.git",
                "html_url": "https://gist.github.com/9913820",
                "files": 
            
            {
            
                "2013-06-11-use-mock-in-python.markdown": 
            
                {
                    "filename": "2013-06-11-use-mock-in-python.markdown",
                    "type": "text/plain",
                    "language": "Markdown",
                    "raw_url": "https://gist.githubusercontent.com/jcouyang/9913820/raw/b9286122114f690ee42243a207eb3def00f65bb8/2013-06-11-use-mock-in-python.markdown",
                    "size": 7243
                }
            
            },
            "public": true,
            "created_at": "2014-04-01T13:19:25Z",
            "updated_at": "2014-04-01T13:19:25Z",
            "description": "Evernote with emacs and org-mode",
            "comments": 0,
            "user": null,
            "comments_url": "https://api.github.com/gists/9913820/comments",
            "owner":
            
                {
                    "login": "jcouyang",
                    "id": 1235045,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jcouyang",
                    "html_url": "https://github.com/jcouyang",
                    "followers_url": "https://api.github.com/users/jcouyang/followers",
                    "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
                    "organizations_url": "https://api.github.com/users/jcouyang/orgs",
                    "repos_url": "https://api.github.com/users/jcouyang/repos",
                    "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jcouyang/received_events",
                    "type": "User",
                    "site_admin": false
                }
            
            }
            
            ]

### List All Gists [GET]
+ Parameters
    + since (optional, string) ... Timestamp in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ` Only gists updated at or after this time are returned.

+ Response 200

    [Gists Collection][]

### Create a Gist [POST]
To create a new Gist simply provide a JSON hash of the *description* and *content* attributes for the new Gist. 

This action requires an `access_token` with `gist_write` scope. 

+ Parameters
    + access_token (string, optional) ... Gist Fox API access token.

+ Request (application/json)

        {
            "description": "Description of Gist",
            "content": "String content"
        }

+ Response 201

    [Gist][]

## Star [/gists/{id}/star{?access_token}]
Star resource represents a Gist starred status. 

The Star resource has the following attribute:

- starred

+ Parameters
    + id (string) ... ID of the gist in the form of a hash
    + access_token (string, optional) ... Gist Fox API access token.    

+ Model (application/json)

    HAL+JSON representation of Star Resource.

    + Headers

            Link: <http:/api.gistfox.com/gists/42/star>;rel="self"

    + Body

            {
                "_links": {
                    "self": { "href": "/gists/42/star" },
                },
                "starred": true
            }

### Star a Gist [PUT]
This action requires an `access_token` with `gist_write` scope. 

+ Response 204

### Unstar a Gist [DELETE]
This action requires an `access_token` with `gist_write` scope. 

+ Response 204

### Check if a Gist is Starred [GET]
+ Response 200

    [Star][]

# Group Access Authorization and Control
Access and Control of *Gist Fox API* OAuth token.

## Authorization [/authorization]
Authorization Resource represents an authorization granted to the user. You can **only** access your own authorization, and only through **Basic Authentication**.

The Authorization Resource has the following attribute:

- token
- scopes

Where *token* represents an OAuth token and *scopes* is an array of scopes granted for the given authorization. At this moment the only available scope is `gist_write`.

+ Model (application/json)

    + Headers

            Link: <http:/api.gistfox.com/authorizations/1>;rel="self"

    + Body

            {
                "_links": {
                    "self": { "href": "/authorizations" },
                },
                "scopes": [
                    "gist_write"
                ],
                "token": "abc123"
            }

### Retrieve Authorization [GET]
+ Request
    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 200

    [Authorization][]

### Create Authorization [POST]
+ Request (application/json)
    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

    + Body

            {
                "scopes": [
                    "gist_write"
                ]
            }

+ Response 201

    [Authorization][]

### Remove an Authorization [DELETE]
+ Request
    + Headers

            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 204    

## Login [login/oauth/authorize{?client_id=005a3ed2cec4cb179828}]
### redirect back with code [GET]
+ Response 301
    + Headers

            Location: "/?hehe=da"
